/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { AcceptInvitation201DataUser } from './acceptInvitation201DataUser';

export type AcceptInvitation201Data = {
  accessToken: string;
  expiresIn: number;
  /** Identity v1 user profile and JWT context. */
  user: AcceptInvitation201DataUser;
};
