/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

export type AcceptInvitation201DataUserRole = typeof AcceptInvitation201DataUserRole[keyof typeof AcceptInvitation201DataUserRole];


export const AcceptInvitation201DataUserRole = {
  PLATFORM_OWNER: 'PLATFORM_OWNER',
  ADMINISTRADOR: 'ADMINISTRADOR',
  GERENTE: 'GERENTE',
  OPERADOR: 'OPERADOR',
} as const;
