/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { AcceptInvitation201DataUserAccountType } from './acceptInvitation201DataUserAccountType';
import type { AcceptInvitation201DataUserRole } from './acceptInvitation201DataUserRole';
import type { AcceptInvitation201DataUserStatus } from './acceptInvitation201DataUserStatus';

/**
 * Identity v1 user profile and JWT context.
 */
export type AcceptInvitation201DataUser = {
  id: string;
  uuid: string;
  email: string;
  firstName: string;
  lastName: string;
  accountType: AcceptInvitation201DataUserAccountType;
  /** @nullable */
  organizationId: string | null;
  role: AcceptInvitation201DataUserRole;
  status: AcceptInvitation201DataUserStatus;
};
