/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

export type ActivateCampaign200DataStatus = typeof ActivateCampaign200DataStatus[keyof typeof ActivateCampaign200DataStatus];


export const ActivateCampaign200DataStatus = {
  ACTIVE: 'ACTIVE',
} as const;
