/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { AssignConversationTag200Data } from './assignConversationTag200Data';

/**
 * Envelope for tag assignment/removal results (FR-006).
 */
export type AssignConversationTag200 = {
  data: AssignConversationTag200Data;
};
