/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Payload for assigning or transferring an advisor to a conversation (HG-4).
 */
export type AssignConversationBody = {
  /** uuid of the advisor user (must belong to the conversation's organization). */
  advisorId: string;
};
