/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CloseConversation200Data } from './closeConversation200Data';

/**
 * Envelope for lifecycle transitions (close/archive/reopen, FR-005).
 */
export type CloseConversation200 = {
  data: CloseConversation200Data;
};
