/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * At least one criterion required when present.
 */
export type CreateCampaignBodySegment = ({
  /**
     * Partial match, case-insensitive, over the customer city.
     * @maxLength 200
     */
  city?: string;
  /** uuid of the purchased product. */
  productId?: string;
  /**
     * Lower bound on purchaseDate. Date-only (`YYYY-MM-DD`) includes the
     * whole requested day.
     */
  purchaseFrom?: string;
  /**
     * Upper bound on purchaseDate. Date-only (`YYYY-MM-DD`) includes the
     * whole requested day.
     */
  purchaseTo?: string;
  customerStatus?: 'ACTIVE' | 'INACTIVE' | 'BLOCKED';
});
