/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCustomerBodyStatus } from './createCustomerBodyStatus';

/**
 * Request body to create a customer.
 */
export type CreateCustomerBody = {
  /**
     * Client code, unique within the organization. Immutable after creation.
     * @maxLength 50
     */
  codcli: string;
  /** @maxLength 200 */
  name: string;
  /**
     * Free-form phone string (E.164 is not enforced in v1).
     * @maxLength 30
     */
  phone?: string;
  email?: string;
  /** @maxLength 200 */
  address?: string;
  /** @maxLength 200 */
  city?: string;
  /** Defaults to ACTIVE. BLOCKED is reserved and inert in v1. */
  status?: CreateCustomerBodyStatus;
  /** Only accepted for PLATFORM_OWNER; required for them. Organization users must not send it. */
  organizationId?: string;
};
