/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProductBodyStatus } from './createProductBodyStatus';

/**
 * Request body to create a product.
 */
export type CreateProductBody = {
  /**
     * ERP-facing reference; immutable after creation. Duplicate codes within the organization return 409 CONFLICT (schema.prisma:128).
     * @maxLength 50
     */
  code: string;
  /** @maxLength 200 */
  name: string;
  /**
     * Free-text category (no catalog in v1).
     * @maxLength 100
     */
  category?: string;
  /** Defaults to ACTIVE. */
  status?: CreateProductBodyStatus;
  /** Only accepted for PLATFORM_OWNER; required for them. Organization users must not send it (400 VALIDATION_ERROR). */
  organizationId?: string;
};
