/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CreateFollowUpSequence400ErrorDetails } from './createFollowUpSequence400ErrorDetails';

export type CreateFollowUpSequence400Error = {
  code: string;
  message: string;
  /** Optional error details */
  details?: CreateFollowUpSequence400ErrorDetails;
};
