/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

export type CreateCampaign201DataStatus = typeof CreateCampaign201DataStatus[keyof typeof CreateCampaign201DataStatus];


export const CreateCampaign201DataStatus = {
  DRAFT: 'DRAFT',
} as const;
