/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Payload for creating a conversation tag (ADMINISTRADOR, GERENTE).
 */
export type CreateConversationTagBody = {
  /**
     * Tag name, unique within the organization.
     * @minLength 1
     * @maxLength 50
     */
  name: string;
  /**
     * Optional hex color, e.g. "#0EA5E9".
     * @pattern ^#[0-9a-fA-F]{6}$
     */
  color?: string;
};
