/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Warranty duration in months (catalog values).
 */
export type CreateFollowUpSequenceBodyWarrantyMonths = typeof CreateFollowUpSequenceBodyWarrantyMonths[keyof typeof CreateFollowUpSequenceBodyWarrantyMonths];


export const CreateFollowUpSequenceBodyWarrantyMonths = {
  NUMBER_12: 12,
  NUMBER_15: 15,
  NUMBER_18: 18,
  NUMBER_24: 24,
} as const;
