/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

export type CreateImportJob201DataType = typeof CreateImportJob201DataType[keyof typeof CreateImportJob201DataType];


export const CreateImportJob201DataType = {
  CUSTOMERS: 'CUSTOMERS',
  PURCHASES: 'PURCHASES',
  PRODUCTS: 'PRODUCTS',
} as const;
