/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCustomer201Data } from './createCustomer201Data';

/**
 * Envelope for a single customer operation.
 */
export type CreateCustomer201 = {
  /** Customer entity as persisted (v1). */
  data: CreateCustomer201Data;
};
