/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCampaignBodySegment } from './createCampaignBodySegment';
import type { CreateCampaignBodyType } from './createCampaignBodyType';

/**
 * Payload to create a campaign. The campaign is always persisted as DRAFT.
 */
export type CreateCampaignBody = {
  /**
     * @minLength 1
     * @maxLength 120
     */
  name: string;
  /** @maxLength 1000 */
  description?: string;
  type: CreateCampaignBodyType;
  /**
     * Message template, free text with {customerName}/{productName}/
     * {organizationName} placeholders.
     * @minLength 1
     * @maxLength 4096
     */
  template: string;
  /**
     * Message for the +3 days stage. When defined, replaces `template`
     * for that stage.
     * @maxLength 4096
     */
  templateD3?: string;
  /**
     * Message for the +6 months stage. When defined, replaces `template`
     * for that stage.
     * @maxLength 4096
     */
  templateD180?: string;
  /**
     * Message for the +12 months stage. When defined, replaces `template`
     * for that stage.
     * @maxLength 4096
     */
  templateD365?: string;
  /** At least one criterion required when present. */
  segment?: CreateCampaignBodySegment;
  /** Optional scheduled start (automations are scheduled for max(startAt, now)). */
  startAt?: string;
};
