/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CreateFollowUpSequenceBodyStagesItem } from './createFollowUpSequenceBodyStagesItem';
import type { CreateFollowUpSequenceBodyWarrantyMonths } from './createFollowUpSequenceBodyWarrantyMonths';

/**
 * Payload to create a follow-up sequence.
 */
export type CreateFollowUpSequenceBody = {
  /**
     * @minLength 1
     * @maxLength 120
     */
  name: string;
  /** @maxLength 1000 */
  description?: string;
  /** Warranty duration in months (catalog values). */
  warrantyMonths: CreateFollowUpSequenceBodyWarrantyMonths;
  /**
     * At least one stage required.
     * @minItems 1
     */
  stages: CreateFollowUpSequenceBodyStagesItem[];
};
