/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CreateFollowUpSequenceBodyStagesItemAnchor } from './createFollowUpSequenceBodyStagesItemAnchor';

/**
 * A stage in a follow-up sequence.
 */
export type CreateFollowUpSequenceBodyStagesItem = {
  /**
     * @minLength 1
     * @maxLength 120
     */
  name: string;
  /**
     * Temporal reference for offsetDays.
     * PURCHASE_DATE = offset measured from the purchase date;
     * WARRANTY_EXPIRY = offset measured from the warranty expiration date.
     * Defaults to WARRANTY_EXPIRY when omitted (preserves legacy behavior).
     */
  anchor?: CreateFollowUpSequenceBodyStagesItemAnchor;
  /**
     * Offset in days from the stage anchor.
     * Per-anchor bounds:
     * - PURCHASE_DATE: 0..365 (negative offsets rejected).
     * - WARRANTY_EXPIRY: -365..730 (negative = before expiration, 0 = day of
     *   expiration, positive = after expiration).
     * @minimum -365
     * @maximum 730
     */
  offsetDays: number;
  /**
     * Message template with placeholders: {customerName}, {productName}, {organizationName}, {warrantyExpiresAt}.
     * @minLength 1
     * @maxLength 4096
     */
  template: string;
  /**
     * Optional repurchase/renovation message used when the stage date already
     * passed at campaign activation time (HG-SEM-03). Falls back to the
     * campaign base template when absent.
     * @maxLength 4096
     */
  templateOnPast?: string;
};
