/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCustomer201DataStatus } from './createCustomer201DataStatus';

/**
 * Customer entity as persisted (v1).
 */
export type CreateCustomer201Data = {
  id: string;
  uuid: string;
  organizationId: string;
  /**
     * Client code, unique within the organization.
     * @maxLength 50
     */
  codcli: string;
  /** @maxLength 200 */
  name: string;
  /**
     * @maxLength 30
     * @nullable
     */
  phone?: string | null;
  /** @nullable */
  email?: string | null;
  /**
     * @maxLength 200
     * @nullable
     */
  address?: string | null;
  /**
     * @maxLength 200
     * @nullable
     */
  city?: string | null;
  /** BLOCKED is reserved and inert in v1. */
  status: CreateCustomer201DataStatus;
  createdAt: string;
  updatedAt: string;
  /**
     * Set on soft delete; deleted customers are never returned.
     * @nullable
     */
  deletedAt?: string | null;
  /**
     * User id that created the record.
     * @nullable
     */
  createdBy?: string | null;
  /**
     * User id of the last update.
     * @nullable
     */
  updatedBy?: string | null;
  /**
     * User id that performed the soft delete.
     * @nullable
     */
  deletedBy?: string | null;
};
