/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CreateQuickReply201Data } from './createQuickReply201Data';

/**
 * Envelope for a single quick reply resource.
 */
export type CreateQuickReply201 = {
  /** Full quick reply representation (catalog detail). */
  data: CreateQuickReply201Data;
};
