/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * A stage in a follow-up sequence.
 */
export type CreateFollowUpSequenceBodyStagesItem = {
  /**
     * @minLength 1
     * @maxLength 120
     */
  name: string;
  /**
     * Offset in days from warranty expiration date.
     * Negative = before expiration, 0 = day of expiration, positive = after expiration.
     * @minimum -365
     * @maximum 365
     */
  offsetDays: number;
  /**
     * Message template with placeholders: {customerName}, {productName}, {organizationName}, {warrantyExpiresAt}.
     * @minLength 1
     * @maxLength 4096
     */
  template: string;
};
