/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Payload for adding an append-only note to a conversation.
 */
export type CreateConversationNoteBody = {
  /**
     * Note content (PII — never logged).
     * @minLength 1
     * @maxLength 4000
     */
  content: string;
};
