/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CreateImportJobBodyType } from './createImportJobBodyType';

/**
 * Multipart/form-data fields of POST /imports. The file is a binary part
 * named `file`. PLATFORM_OWNER additionally sends `organizationId`; sending it
 * as an ORGANIZATION user returns 400 (HG-12).
 */
export type CreateImportJobBody = {
  /** CSV or XLSX file, max 25 MB (FR-002). */
  file?: Blob;
  type?: CreateImportJobBodyType;
  /** Required for PLATFORM_OWNER only. */
  organizationId?: string;
};
