/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CreateConversationNote201Data } from './createConversationNote201Data';

/**
 * Envelope for a single conversation note resource.
 */
export type CreateConversationNote201 = {
  /** Append-only conversation note written by an advisor (FR-007, HG-2). */
  data: CreateConversationNote201Data;
};
