/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CreatePurchaseBodyStatus } from './createPurchaseBodyStatus';

/**
 * Request body to create a purchase.
 */
export type CreatePurchaseBody = {
  /** Existing customer within the organization; otherwise 400 VALIDATION_ERROR. */
  customerId: string;
  /** Existing product within the organization (v1 validates existence only, HG-3); otherwise 400 VALIDATION_ERROR. */
  productId: string;
  /**
     * Immutable after creation. Duplicate tuples return 409 CONFLICT (CP-005).
     * @maxLength 50
     */
  invoiceNumber: string;
  purchaseDate: string;
  /**
     * Units of the purchase; capped at the Prisma Int maximum (int4).
     * @minimum 1
     * @maximum 2147483647
     */
  quantity: number;
  /**
     * Total purchase value in USD as a string (HG-7).
     * @pattern ^\d{1,10}(\.\d{1,2})?$
     */
  value: string;
  /** Defaults to COMPLETED. */
  status?: CreatePurchaseBodyStatus;
  /**
     * Optional override of product warranty duration in months.
     * @minimum 1
     * @maximum 24
     */
  warrantyMonths?: number;
  /** Only accepted for PLATFORM_OWNER; required for them. Organization users must not send it (400 VALIDATION_ERROR). */
  organizationId?: string;
};
