/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Defaults to COMPLETED.
 */
export type CreatePurchaseBodyStatus = typeof CreatePurchaseBodyStatus[keyof typeof CreatePurchaseBodyStatus];


export const CreatePurchaseBodyStatus = {
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
} as const;
