/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

export type CreateImportJob200DataStatus = typeof CreateImportJob200DataStatus[keyof typeof CreateImportJob200DataStatus];


export const CreateImportJob200DataStatus = {
  PENDING: 'PENDING',
  VALIDATING: 'VALIDATING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  PARTIAL: 'PARTIAL',
  CANCELLED: 'CANCELLED',
} as const;
