/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Defaults to ACTIVE. BLOCKED is reserved and inert in v1.
 */
export type CreateCustomerBodyStatus = typeof CreateCustomerBodyStatus[keyof typeof CreateCustomerBodyStatus];


export const CreateCustomerBodyStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  BLOCKED: 'BLOCKED',
} as const;
