/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProduct201DataStatus } from './createProduct201DataStatus';

/**
 * Full product record as returned by get/create/update operations.
 */
export type CreateProduct201Data = {
  id: string;
  uuid: string;
  /** ERP-facing reference; immutable after creation. */
  code: string;
  name: string;
  /**
     * Free-text category (no catalog in v1).
     * @nullable
     */
  category?: string | null;
  status: CreateProduct201DataStatus;
  createdAt: string;
  updatedAt: string;
  /**
     * Actor user id from the JWT on creation.
     * @nullable
     */
  createdBy?: string | null;
  /**
     * Actor user id from the JWT on last update.
     * @nullable
     */
  updatedBy?: string | null;
};
