/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CreateFollowUpSequence403Error } from './createFollowUpSequence403Error';

export type CreateFollowUpSequence403 = {
  error?: CreateFollowUpSequence403Error;
};
