/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { CreateImportJob200Data } from './createImportJob200Data';

/**
 * Envelope for a single import job operation.
 */
export type CreateImportJob200 = {
  /**
     * Import job. `filePath` and the full internal `errors` payload are never
     * exposed (NR-006, FR-024); only `errorsSummary` is returned.
     */
  data: CreateImportJob200Data;
};
