/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Defaults to COMPLETED. Changed freely via PATCH in v1 (HG-7).
 */
export type CreatePurchase201DataStatus = typeof CreatePurchase201DataStatus[keyof typeof CreatePurchase201DataStatus];


export const CreatePurchase201DataStatus = {
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
} as const;
