/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteFollowUpSequence400Error } from './deleteFollowUpSequence400Error';

/**
 * Standard error response envelope.
 */
export type DeleteFollowUpSequence400 = {
  error: DeleteFollowUpSequence400Error;
};
