/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetAutomation200Data } from './getAutomation200Data';

/**
 * Envelope for a single automation resource.
 */
export type GetAutomation200 = {
  /** Full automation representation with purchase and customer context. */
  data: GetAutomation200Data;
};
