/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetAutomation200DataCustomer } from './getAutomation200DataCustomer';
import type { GetAutomation200DataPurchase } from './getAutomation200DataPurchase';

/**
 * Full automation representation with purchase and customer context.
 */
export type GetAutomation200Data = ({
  uuid: string;
  /**
     * Lifecycle of an automation. EXECUTED is a final state (no execution
     * engine in v1). ERROR is used when the automation could not be
     * executed; PAUSED is reserved for future deferred flows.
     */
  status: 'PENDING' | 'SCHEDULED' | 'EXECUTED' | 'CANCELLED' | 'ERROR' | 'PAUSED';
  scheduledDate: string;
  /** @nullable */
  executedDate: string | null;
  /** Reserved for AU-010 (priority scheduling); always 0 in v1. */
  priority: number;
  /** uuid of the triggering purchase. */
  purchaseId: string;
  /** uuid of the owning commercial cycle. */
  commercialCycleId: string;
  createdAt: string;
}) & ({
  organizationId: string;
  /**
     * Not linked to a campaign in v1; reserved for future modules.
     * @nullable
     */
  campaignId: string | null;
  purchase: GetAutomation200DataPurchase;
  customer: GetAutomation200DataCustomer;
});
