/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetCommercialCycle200DataAutomationsItem } from './getCommercialCycle200DataAutomationsItem';

/**
 * Full commercial cycle representation with its automations.
 */
export type GetCommercialCycle200Data = ({
  uuid: string;
  status: 'ACTIVE' | 'FINISHED' | 'CANCELLED';
  /** Same as the triggering purchase date (AU-005). */
  startDate: string;
  /**
     * Set when the cycle is cancelled (AU-003).
     * @nullable
     */
  endDate: string | null;
  /** uuid of the triggering purchase. */
  purchaseId: string;
  createdAt: string;
}) & {
  automations: GetCommercialCycle200DataAutomationsItem[];
};
