/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetConversation200DataNotesItemAuthor } from './getConversation200DataNotesItemAuthor';

/**
 * Append-only conversation note written by an advisor (FR-007, HG-2).
 */
export type GetConversation200DataNotesItem = {
  uuid: string;
  /** Note author (the authenticated advisor). */
  author: GetConversation200DataNotesItemAuthor;
  /**
     * @minLength 1
     * @maxLength 4000
     */
  content: string;
  createdAt: string;
};
