/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetConversation200DataMessagesItem } from './getConversation200DataMessagesItem';
import type { GetConversation200DataNotesItem } from './getConversation200DataNotesItem';

/**
 * Full conversation representation with message history and the append-only notes log.
 */
export type GetConversation200Data = (({
  uuid: string;
  /**
     * Channel type. v1 exposes WHATSAPP_CLIENTS only; WHATSAPP_SOCIAL is
     * reserved for future kits.
     */
  channel: 'WHATSAPP_CLIENTS' | 'WHATSAPP_SOCIAL';
  /**
     * Conversation lifecycle. v1 creates OPEN conversations only (R-010);
     * CLOSED/ARCHIVED transitions belong to the inbox kit (018).
     */
  status: 'OPEN' | 'CLOSED' | 'ARCHIVED';
  /**
     * uuid of the linked customer, or null when the inbound number could not
     * be matched (HG-8). Conversations opened by outbound sends always link
     * the customer (R-010).
     * @nullable
     */
  customerId: string | null;
  /**
     * Internal advisor user id; the public advisor reference is `advisor.uuid`.
     * @nullable
     */
  advisorId: string | null;
  /**
     * Assigned advisor (inbox kit 018, FR-004). Null when unassigned.
     * @nullable
     */
  advisor?: {
  uuid: string;
  firstName: string;
  lastName: string;
} | null;
  /**
     * createdAt of the most recent message, or null when empty.
     * @nullable
     */
  lastMessageAt: string | null;
  /** Number of non-deleted messages in the conversation. */
  messageCount: number;
  createdAt: string;
}) & ({
  /** Active tag assignments (FR-006), preloaded without N+1. */
  tags: ({
  uuid: string;
  name: string;
  /** @nullable */
  color: string | null;
})[];
})) & {
  /** Message history in chronological order (FR-008, NR-003). */
  messages: GetConversation200DataMessagesItem[];
  /** Append-only advisor notes in chronological order (FR-007, HG-2). */
  notes: GetConversation200DataNotesItem[];
};
