/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Lightweight automation representation for list endpoints.
 */
export type GetCommercialCycle200DataAutomationsItem = ({
  uuid: string;
  /**
     * Lifecycle of an automation. EXECUTED is a final state (no execution
     * engine in v1). ERROR is used when the automation could not be
     * executed; PAUSED is reserved for future deferred flows.
     */
  status: 'PENDING' | 'SCHEDULED' | 'EXECUTED' | 'CANCELLED' | 'ERROR' | 'PAUSED';
  scheduledDate: string;
  /** @nullable */
  executedDate: string | null;
  /** Reserved for AU-010 (priority scheduling); always 0 in v1. */
  priority: number;
  /** uuid of the triggering purchase. */
  purchaseId: string;
  /** uuid of the owning commercial cycle. */
  commercialCycleId: string;
  createdAt: string;
});
