/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

export type GetCampaign200DataFollowUpSequenceWarrantyMonths = typeof GetCampaign200DataFollowUpSequenceWarrantyMonths[keyof typeof GetCampaign200DataFollowUpSequenceWarrantyMonths];


export const GetCampaign200DataFollowUpSequenceWarrantyMonths = {
  NUMBER_12: 12,
  NUMBER_15: 15,
  NUMBER_18: 18,
  NUMBER_24: 24,
} as const;
