/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetCampaign200DataFollowUpSequenceWarrantyMonths } from './getCampaign200DataFollowUpSequenceWarrantyMonths';

/**
 * Follow-up sequence linked to the campaign, when present.
 * @nullable
 */
export type GetCampaign200DataFollowUpSequence = {
  uuid: string;
  name: string;
  warrantyMonths: GetCampaign200DataFollowUpSequenceWarrantyMonths;
  stageCount: number;
} | null;
