/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetConversation200Data } from './getConversation200Data';

/**
 * Envelope for a single conversation resource.
 */
export type GetConversation200 = {
  /** Full conversation representation with message history and the append-only notes log. */
  data: GetConversation200Data;
};
