/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetCommercialCycle200Data } from './getCommercialCycle200Data';

/**
 * Envelope for a single commercial cycle resource.
 */
export type GetCommercialCycle200 = {
  /** Full commercial cycle representation with its automations. */
  data: GetCommercialCycle200Data;
};
