/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Lightweight message representation for list endpoints.
 */
export type GetConversation200DataMessagesItem = ({
  uuid: string;
  /** uuid of the owning conversation. */
  conversationId: string;
  /**
     * uuid of the automation that produced the message, or null for manual
     * and inbound messages.
     * @nullable
     */
  automationId: string | null;
  /**
     * Message origin. AUTOMATIC (execution engine), MANUAL (REST manual
     * send), INCOMING (webhook) and OUTGOING (agent replies, inbox kit 018).
     */
  type: 'AUTOMATIC' | 'MANUAL' | 'INCOMING' | 'OUTGOING';
  /** WhatsApp text body. */
  content: string;
  direction: 'INBOUND' | 'OUTBOUND';
  /**
     * Delivery lifecycle. OUTBOUND messages persist QUEUED and transition
     * to SENT/FAILED after the provider call (FR-004); DELIVERED/READ are
     * applied from webhook status callbacks (FR-006/FR-007).
     */
  status: 'QUEUED' | 'SENT' | 'DELIVERED' | 'READ' | 'FAILED';
  /** @nullable */
  sentAt: string | null;
  /** @nullable */
  deliveredAt: string | null;
  /** @nullable */
  readAt: string | null;
  createdAt: string;
});
