/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetDashboardCampaigns200DataRecentItem } from './getDashboardCampaigns200DataRecentItem';
import type { GetDashboardCampaigns200DataUpcomingItem } from './getDashboardCampaigns200DataUpcomingItem';

export type GetDashboardCampaigns200Data = {
  /** Last 10 campaigns ordered by createdAt desc. */
  recent: GetDashboardCampaigns200DataRecentItem[];
  /** ACTIVE campaigns with future startAt ordered ascending (take 10). */
  upcoming: GetDashboardCampaigns200DataUpcomingItem[];
};
