/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetDashboardActivity200DataItemMetadata } from './getDashboardActivity200DataItemMetadata';

/**
 * Single entry of the activity feed (read of the org audit trail).
 */
export type GetDashboardActivity200DataItem = {
  uuid: string;
  /** Source module that wrote the audit row (e.g. campaigns, identity). */
  module: string;
  /** Audit action code (e.g. campaign.activate). */
  action: string;
  /** @nullable */
  description: string | null;
  /**
     * Extra context as written by the source module (ids/counts only).
     * @nullable
     */
  metadata: GetDashboardActivity200DataItemMetadata;
  /** @nullable */
  userId: string | null;
  /**
     * Display name "<firstName> <lastName>" of the acting user.
     * @nullable
     */
  userName: string | null;
  createdAt: string;
};
