/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetDashboardSummary200DataAutomations } from './getDashboardSummary200DataAutomations';
import type { GetDashboardSummary200DataCampaigns } from './getDashboardSummary200DataCampaigns';
import type { GetDashboardSummary200DataConversations } from './getDashboardSummary200DataConversations';
import type { GetDashboardSummary200DataCustomers } from './getDashboardSummary200DataCustomers';
import type { GetDashboardSummary200DataMessages } from './getDashboardSummary200DataMessages';
import type { GetDashboardSummary200DataPurchases } from './getDashboardSummary200DataPurchases';

/**
 * Global KPIs of the organization (GET /dashboard/summary), computed
 * on-the-fly from the existing org-scoped tables (HG-1). All counts
 * exclude soft-deleted records.
 */
export type GetDashboardSummary200Data = {
  customers: GetDashboardSummary200DataCustomers;
  purchases: GetDashboardSummary200DataPurchases;
  automations: GetDashboardSummary200DataAutomations;
  messages: GetDashboardSummary200DataMessages;
  conversations: GetDashboardSummary200DataConversations;
  campaigns: GetDashboardSummary200DataCampaigns;
};
