/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

export type GetDashboardCampaigns200DataRecentItemStatus = typeof GetDashboardCampaigns200DataRecentItemStatus[keyof typeof GetDashboardCampaigns200DataRecentItemStatus];


export const GetDashboardCampaigns200DataRecentItemStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  FINISHED: 'FINISHED',
  CANCELLED: 'CANCELLED',
} as const;
