/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

export type GetDashboardCampaigns200DataRecentItemType = typeof GetDashboardCampaigns200DataRecentItemType[keyof typeof GetDashboardCampaigns200DataRecentItemType];


export const GetDashboardCampaigns200DataRecentItemType = {
  AUTOMATIC: 'AUTOMATIC',
  MANUAL: 'MANUAL',
  REPURCHASE: 'REPURCHASE',
  SPECIAL: 'SPECIAL',
} as const;
