/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

export type GetDashboardSummary200DataMessages = {
  /** Messages with status SENT. */
  sent: number;
  /** Messages with status QUEUED. */
  pending: number;
};
