/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Extra context as written by the source module (ids/counts only).
 * @nullable
 */
export type GetDashboardActivity200DataItemMetadata = { [key: string]: unknown } | null;
