/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetDashboardActivity200DataItem } from './getDashboardActivity200DataItem';

/**
 * Envelope for the activity feed (GET /dashboard/activity).
 */
export type GetDashboardActivity200 = {
  /** Last 20 audit entries of the organization, newest first. */
  data: GetDashboardActivity200DataItem[];
};
