/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetDashboardCampaigns200DataUpcomingItemStatus } from './getDashboardCampaigns200DataUpcomingItemStatus';
import type { GetDashboardCampaigns200DataUpcomingItemType } from './getDashboardCampaigns200DataUpcomingItemType';

/**
 * Lightweight campaign row for the dashboard campaigns panel.
 */
export type GetDashboardCampaigns200DataUpcomingItem = {
  uuid: string;
  name: string;
  type: GetDashboardCampaigns200DataUpcomingItemType;
  status: GetDashboardCampaigns200DataUpcomingItemStatus;
  /**
     * Scheduled start; upcoming campaigns have a future startAt.
     * @nullable
     */
  startAt: string | null;
  createdAt: string;
};
