/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetDashboardCampaigns200DataRecentItemStatus } from './getDashboardCampaigns200DataRecentItemStatus';
import type { GetDashboardCampaigns200DataRecentItemType } from './getDashboardCampaigns200DataRecentItemType';

/**
 * Lightweight campaign row for the dashboard campaigns panel.
 */
export type GetDashboardCampaigns200DataRecentItem = {
  uuid: string;
  name: string;
  type: GetDashboardCampaigns200DataRecentItemType;
  status: GetDashboardCampaigns200DataRecentItemStatus;
  /**
     * Scheduled start; upcoming campaigns have a future startAt.
     * @nullable
     */
  startAt: string | null;
  createdAt: string;
};
