/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetDashboardSummary200Data } from './getDashboardSummary200Data';

/**
 * Envelope for the dashboard summary (GET /dashboard/summary).
 */
export type GetDashboardSummary200 = {
  /**
     * Global KPIs of the organization (GET /dashboard/summary), computed
     * on-the-fly from the existing org-scoped tables (HG-1). All counts
     * exclude soft-deleted records.
     */
  data: GetDashboardSummary200Data;
};
