/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

export type GetFollowUpSequence200Data = ({
  uuid: string;
  name: string;
  /** @nullable */
  description?: string | null;
  warrantyMonths: 12 | 15 | 18 | 24;
  /** Number of stages in the sequence. */
  stageCount: number;
  createdAt: string;
}) & {
  stages: {
  uuid: string;
  name: string;
  offsetDays: number;
  template: string;
  createdAt: string;
}[];
  updatedAt: string;
};
