/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetFollowUpSequence404Error } from './getFollowUpSequence404Error';

/**
 * Standard error response envelope.
 */
export type GetFollowUpSequence404 = {
  error: GetFollowUpSequence404Error;
};
