/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetFollowUpSequence200Data } from './getFollowUpSequence200Data';

export type GetFollowUpSequence200 = {
  data: GetFollowUpSequence200Data;
};
