/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetFollowUpSequence404ErrorDetails } from './getFollowUpSequence404ErrorDetails';

export type GetFollowUpSequence404Error = {
  code: string;
  message: string;
  /** Optional error details */
  details?: GetFollowUpSequence404ErrorDetails;
};
