/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetImportJob200DataErrorsSummary } from './getImportJob200DataErrorsSummary';
import type { GetImportJob200DataStatus } from './getImportJob200DataStatus';
import type { GetImportJob200DataType } from './getImportJob200DataType';

/**
 * Import job. `filePath` and the full internal `errors` payload are never
 * exposed (NR-006, FR-024); only `errorsSummary` is returned.
 */
export type GetImportJob200Data = {
  uuid: string;
  type: GetImportJob200DataType;
  status: GetImportJob200DataStatus;
  /** Original basename, sanitized (NR-006). */
  fileName: string;
  /** @minimum 0 */
  totalRecords: number;
  /** @minimum 0 */
  processedRecords: number;
  /** @minimum 0 */
  errorRecords: number;
  errorsSummary: GetImportJob200DataErrorsSummary;
  /** @nullable */
  startedAt: string | null;
  /** @nullable */
  completedAt: string | null;
  createdAt: string;
  updatedAt: string;
};
