/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrganization200DataOrganization } from './getOrganization200DataOrganization';

export type GetOrganization200Data = {
  organization?: GetOrganization200DataOrganization;
};
