/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetPurchase200Data } from './getPurchase200Data';

/**
 * Envelope for a single purchase operation.
 */
export type GetPurchase200 = {
  /** Purchase entity as persisted (v1). */
  data: GetPurchase200Data;
};
