/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetPurchaseStats200Data } from './getPurchaseStats200Data';

export type GetPurchaseStats200 = {
  /** Global purchase statistics for the organization, optionally filtered by date range and status. */
  data: GetPurchaseStats200Data;
};
