/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetProduct200Data } from './getProduct200Data';

/**
 * Envelope for a single product operation.
 */
export type GetProduct200 = {
  /** Full product record as returned by get/create/update operations. */
  data: GetProduct200Data;
};
