/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { GetPurchaseStatsStatus } from './getPurchaseStatsStatus';

export type GetPurchaseStatsParams = {
/**
 * Lower bound on purchaseDate. Date-only (`YYYY-MM-DD`) includes the
 * whole requested day.
 */
dateFrom?: string;
/**
 * Upper bound on purchaseDate. Date-only (`YYYY-MM-DD`) includes the
 * whole requested day.
 */
dateTo?: string;
status?: GetPurchaseStatsStatus;
};
