/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Global purchase statistics for the organization, optionally filtered by date range and status.
 */
export type GetPurchaseStats200Data = {
  /** Total purchases matching the filters. */
  total: number;
  /** Sum of purchase values as a string. */
  totalValue: string;
  /** Sum of purchased units. */
  units: number;
  /** Purchases whose warranty expiration is today or later. */
  activeWarranties: number;
  /** Distinct customers with at least one matching purchase. */
  customers: number;
};
