/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListProductsStatus } from './listProductsStatus';

export type ListProductsParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Case-insensitive match over code, name, or category.
 */
search?: string;
status?: ListProductsStatus;
/**
 * Exact match over the free-text category.
 */
category?: string;
/**
 * Lower bound on createdAt. Date-only (`YYYY-MM-DD`) means the start
 * of that day (`>= 00:00:00` UTC); a full ISO datetime keeps its exact
 * instant.
 */
createdFrom?: string;
/**
 * Upper bound on createdAt. Date-only (`YYYY-MM-DD`) includes the
 * whole requested day (`<= 23:59:59.999` UTC); a full ISO datetime
 * keeps its exact instant.
 */
createdTo?: string;
/**
 * Field sorted by; "-" prefix means descending. Defaults to -createdAt.
 * @pattern ^-?(code|name|category|status|createdAt|updatedAt)$
 */
sort?: string;
};
