/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Pagination metadata for collection responses.
 */
export type ListFollowUpSequences200Meta = {
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  limit: number;
  /** @minimum 0 */
  total: number;
  /** @minimum 0 */
  pages: number;
};
