/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListConversationsAssigned } from './listConversationsAssigned';
import type { ListConversationsChannel } from './listConversationsChannel';
import type { ListConversationsStatus } from './listConversationsStatus';

export type ListConversationsParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exact match over the conversation status.
 */
status?: ListConversationsStatus;
/**
 * Filter by assignment: `true` only conversations with an advisor,
 * `false` only unassigned ones (inbox kit 018, FR-004).
 */
assigned?: ListConversationsAssigned;
/**
 * Comma-separated tag uuids; returns conversations holding any of
 * the given tags (any-of, inbox kit 018, FR-006).
 */
tagIds?: string;
/**
 * Exact match over the channel type.
 */
channel?: ListConversationsChannel;
/**
 * uuid of the linked customer.
 */
customerId?: string;
/**
 * uuid of the assigned advisor (inbox kit 018, FR-004).
 */
advisorId?: string;
/**
 * Lower bound on createdAt. Date-only (`YYYY-MM-DD`) means the start
 * of that day; a full ISO datetime keeps its exact instant.
 */
createdFrom?: string;
/**
 * Upper bound on createdAt. Date-only (`YYYY-MM-DD`) includes the
 * whole requested day.
 */
createdTo?: string;
/**
 * Field sorted by; "-" prefix means descending. Defaults to -createdAt.
 * @pattern ^-?(createdAt|updatedAt|status)$
 */
sort?: string;
};
