/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListPurchases200DataItem } from './listPurchases200DataItem';
import type { ListPurchases200Meta } from './listPurchases200Meta';

/**
 * Envelope for the paginated purchase list.
 */
export type ListPurchases200 = {
  data: ListPurchases200DataItem[];
  meta: ListPurchases200Meta;
};
