/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListFollowUpSequences200DataItemWarrantyMonths } from './listFollowUpSequences200DataItemWarrantyMonths';

export type ListFollowUpSequences200DataItem = {
  uuid: string;
  name: string;
  /** @nullable */
  description?: string | null;
  warrantyMonths: ListFollowUpSequences200DataItemWarrantyMonths;
  /** Number of stages in the sequence. */
  stageCount: number;
  createdAt: string;
};
