/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListProducts200DataItemStatus } from './listProducts200DataItemStatus';

/**
 * Product summary used in list responses.
 */
export type ListProducts200DataItem = {
  id: string;
  uuid: string;
  code: string;
  name: string;
  /** @nullable */
  category?: string | null;
  /**
     * Warranty duration in months from the product catalog (12, 15, 18 or 24).
     * @nullable
     */
  warrantyMonths?: number | null;
  status: ListProducts200DataItemStatus;
  createdAt: string;
  updatedAt: string;
};
