/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListCommercialCycles200DataItemStatus } from './listCommercialCycles200DataItemStatus';

/**
 * Lightweight commercial cycle representation.
 */
export type ListCommercialCycles200DataItem = {
  uuid: string;
  status: ListCommercialCycles200DataItemStatus;
  /** Same as the triggering purchase date (AU-005). */
  startDate: string;
  /**
     * Set when the cycle is cancelled (AU-003).
     * @nullable
     */
  endDate: string | null;
  /** uuid of the triggering purchase. */
  purchaseId: string;
  createdAt: string;
};
