/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListConversationTags200DataItem } from './listConversationTags200DataItem';
import type { ListConversationTags200Meta } from './listConversationTags200Meta';

/**
 * Envelope for the paginated conversation tag catalog.
 */
export type ListConversationTags200 = {
  data: ListConversationTags200DataItem[];
  meta: ListConversationTags200Meta;
};
