/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListCustomersStatus } from './listCustomersStatus';

export type ListCustomersParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Case-insensitive match over name, codcli, phone and email.
 */
search?: string;
status?: ListCustomersStatus;
/**
 * Case-insensitive partial match over city.
 */
city?: string;
createdFrom?: string;
createdTo?: string;
/**
 * Field sorted by; "-" prefix means descending. Defaults to -createdAt.
 * @pattern ^-?(name|codcli|city|status|createdAt|updatedAt)$
 */
sort?: string;
};
