/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListConversationNotes200DataItemAuthor } from './listConversationNotes200DataItemAuthor';

/**
 * Append-only conversation note written by an advisor (FR-007, HG-2).
 */
export type ListConversationNotes200DataItem = {
  uuid: string;
  /** Note author (the authenticated advisor). */
  author: ListConversationNotes200DataItemAuthor;
  /**
     * @minLength 1
     * @maxLength 4000
     */
  content: string;
  createdAt: string;
};
