/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListMessagesDirection } from './listMessagesDirection';
import type { ListMessagesStatus } from './listMessagesStatus';

export type ListMessagesParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * uuid of the owning conversation.
 */
conversationId?: string;
/**
 * Exact match over the delivery status.
 */
status?: ListMessagesStatus;
/**
 * Exact match over the direction.
 */
direction?: ListMessagesDirection;
/**
 * uuid of the producing automation.
 */
automationId?: string;
/**
 * Lower bound on createdAt. Date-only (`YYYY-MM-DD`) means the start
 * of that day; a full ISO datetime keeps its exact instant.
 */
createdFrom?: string;
/**
 * Upper bound on createdAt. Date-only (`YYYY-MM-DD`) includes the
 * whole requested day.
 */
createdTo?: string;
/**
 * Field sorted by; "-" prefix means descending. Defaults to -createdAt.
 * @pattern ^-?(createdAt|sentAt|status)$
 */
sort?: string;
};
