/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListQuickReplies200DataItem } from './listQuickReplies200DataItem';
import type { ListQuickReplies200Meta } from './listQuickReplies200Meta';

/**
 * Envelope for the paginated quick reply catalog.
 */
export type ListQuickReplies200 = {
  data: ListQuickReplies200DataItem[];
  meta: ListQuickReplies200Meta;
};
