/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListAutomations200DataItem } from './listAutomations200DataItem';
import type { ListAutomations200Meta } from './listAutomations200Meta';

/**
 * Envelope for the paginated automation list.
 */
export type ListAutomations200 = {
  data: ListAutomations200DataItem[];
  meta: ListAutomations200Meta;
};
