/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListImportJobs200DataItemErrorsSummarySamplesItem } from './listImportJobs200DataItemErrorsSummarySamplesItem';

export type ListImportJobs200DataItemErrorsSummary = {
  /** @minimum 0 */
  total: number;
  /** Capped at 10 samples. */
  samples: ListImportJobs200DataItemErrorsSummarySamplesItem[];
};
