/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

export type ListCommercialCycles200Meta = {
  /** @minimum 1 */
  page: number;
  /**
     * @minimum 1
     * @maximum 100
     */
  limit: number;
  /** Total matching commercial cycles. */
  total: number;
  pages: number;
};
