/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Tag reference embedded in conversation summaries (active assignments, FR-006).
 */
export type ListConversations200DataItemTagsItem = {
  uuid: string;
  name: string;
  /** @nullable */
  color: string | null;
};
