/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListPurchasesStatus } from './listPurchasesStatus';

export type ListPurchasesParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Case-insensitive match over invoiceNumber.
 */
search?: string;
customerId?: string;
productId?: string;
status?: ListPurchasesStatus;
/**
 * Lower bound on purchaseDate. Date-only (`YYYY-MM-DD`) means the start
 * of that day (`>= 00:00:00` UTC); a full ISO datetime keeps its exact
 * instant.
 */
dateFrom?: string;
/**
 * Upper bound on purchaseDate. Date-only (`YYYY-MM-DD`) includes the
 * whole requested day (`<= 23:59:59.999` UTC); a full ISO datetime
 * keeps its exact instant.
 */
dateTo?: string;
/**
 * Field sorted by; "-" prefix means descending. Defaults to -purchaseDate.
 * @pattern ^-?(purchaseDate|invoiceNumber|quantity|value|status|createdAt|updatedAt)$
 */
sort?: string;
};
