/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListPurchases200DataItemCustomer } from './listPurchases200DataItemCustomer';
import type { ListPurchases200DataItemProduct } from './listPurchases200DataItemProduct';
import type { ListPurchases200DataItemStatus } from './listPurchases200DataItemStatus';

/**
 * Purchase summary used in list responses with nested customer and product summaries.
 */
export type ListPurchases200DataItem = {
  id: string;
  uuid: string;
  invoiceNumber: string;
  purchaseDate: string;
  quantity: number;
  /** Total purchase value as a string. */
  value: string;
  status: ListPurchases200DataItemStatus;
  /**
     * Effective warranty duration in months (product default or explicit override at creation); null when the product has no warranty.
     * @nullable
     */
  warrantyMonths?: number | null;
  /**
     * Warranty expiration computed as purchaseDate + warrantyMonths; null when the product has no warranty.
     * @nullable
     */
  warrantyExpiresAt?: string | null;
  createdAt: string;
  updatedAt: string;
  customer: ListPurchases200DataItemCustomer;
  product: ListPurchases200DataItemProduct;
};
