/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListCommercialCyclesStatus } from './listCommercialCyclesStatus';

export type ListCommercialCyclesParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exact match over the cycle status.
 */
status?: ListCommercialCyclesStatus;
/**
 * uuid of the customer that owns the triggering purchase.
 */
customerId?: string;
/**
 * uuid of the triggering purchase.
 */
purchaseId?: string;
/**
 * Lower bound on createdAt. Date-only (`YYYY-MM-DD`) means the start
 * of that day (`>= 00:00:00` UTC); a full ISO datetime keeps its exact
 * instant.
 */
createdFrom?: string;
/**
 * Upper bound on createdAt. Date-only (`YYYY-MM-DD`) includes the
 * whole requested day (`<= 23:59:59.999` UTC); a full ISO datetime
 * keeps its exact instant.
 */
createdTo?: string;
/**
 * Field sorted by; "-" prefix means descending. Defaults to -createdAt.
 * @pattern ^-?(createdAt|startDate|updatedAt)$
 */
sort?: string;
};
