/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListAutomationsStatus } from './listAutomationsStatus';

export type ListAutomationsParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exact match over the automation status.
 */
status?: ListAutomationsStatus;
/**
 * uuid of the owning commercial cycle.
 */
commercialCycleId?: string;
/**
 * uuid of the owning campaign.
 */
campaignId?: string;
/**
 * uuid of the customer that owns the triggering purchase.
 */
customerId?: string;
/**
 * Lower bound on scheduledDate. Date-only (`YYYY-MM-DD`) means the start
 * of that day; a full ISO datetime keeps its exact instant.
 */
scheduledFrom?: string;
/**
 * Upper bound on scheduledDate. Date-only (`YYYY-MM-DD`) includes the
 * whole requested day.
 */
scheduledTo?: string;
/**
 * Field sorted by; "-" prefix means descending. Defaults to -scheduledDate.
 * @pattern ^-?(scheduledDate|createdAt|updatedAt|status)$
 */
sort?: string;
};
