/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

export type ListImportJobs200DataItemErrorsSummarySamplesItem = {
  /** File row number (1-based). */
  row: number;
  field: string;
  message: string;
  /**
     * Sanitized original value, capped at 200 chars.
     * @nullable
     */
  raw?: string | null;
};
