/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Lightweight campaign representation for list endpoints.
 */
export type ListCampaigns200DataItem = ({
  uuid: string;
  /** Campaign name, 1..120 chars. */
  name: string;
  /**
     * Free-text description, max 1000 chars.
     * @nullable
     */
  description?: string | null;
  /** Informational in v1; does not drive behavior. */
  type: 'AUTOMATIC' | 'MANUAL' | 'REPURCHASE' | 'SPECIAL';
  /**
     * Lifecycle. DRAFT → ACTIVE (activate), ACTIVE ↔ PAUSED,
     * ACTIVE/PAUSED/DRAFT → CANCELLED, ACTIVE → FINISHED (automatic when
     * no SCHEDULED automations remain). FINISHED and CANCELLED are
     * terminal.
     */
  status: 'DRAFT' | 'ACTIVE' | 'PAUSED' | 'FINISHED' | 'CANCELLED';
  /**
     * Scheduled start; automations are scheduled for max(startAt, now).
     * @nullable
     */
  startAt: string | null;
  /** @nullable */
  segment: ({
  /**
     * Partial match, case-insensitive, over the customer city.
     * @maxLength 200
     */
  city?: string;
  /** uuid of the purchased product. */
  productId?: string;
  /**
     * Lower bound on purchaseDate. Date-only (`YYYY-MM-DD`) includes the
     * whole requested day.
     */
  purchaseFrom?: string;
  /**
     * Upper bound on purchaseDate. Date-only (`YYYY-MM-DD`) includes the
     * whole requested day.
     */
  purchaseTo?: string;
  customerStatus?: 'ACTIVE' | 'INACTIVE' | 'BLOCKED';
  /**
     * Lower bound on the purchase warranty expiration date
     * (`warrantyExpiresAt`). Date-only (`YYYY-MM-DD`) includes the whole
     * requested day.
     */
  warrantyExpiresFrom?: string;
  /**
     * Upper bound on the purchase warranty expiration date
     * (`warrantyExpiresAt`). Date-only (`YYYY-MM-DD`) includes the whole
     * requested day.
     */
  warrantyExpiresTo?: string;
  /**
     * Warranty duration in months of the purchased product. Restricted to
     * the catalog values supported by Product/Purchase/FollowUpSequence.
     */
  warrantyMonths?: 12 | 15 | 18 | 24;
}) | null;
  createdAt: string;
}) & {
  /** Total automations generated for the campaign. */
  automationCount: number;
  /** Total EXECUTED automations. */
  executedCount: number;
};
