/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListCustomers200DataItemStatus } from './listCustomers200DataItemStatus';

/**
 * Customer summary used in list responses.
 */
export type ListCustomers200DataItem = {
  id: string;
  uuid: string;
  codcli: string;
  name: string;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  city?: string | null;
  status: ListCustomers200DataItemStatus;
  createdAt: string;
  updatedAt: string;
};
