/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListFollowUpSequencesWarrantyMonths } from './listFollowUpSequencesWarrantyMonths';

export type ListFollowUpSequencesParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Case-insensitive partial match over the sequence name.
 */
search?: string;
/**
 * Exact match over warranty months.
 */
warrantyMonths?: ListFollowUpSequencesWarrantyMonths;
/**
 * Field sorted by; "-" prefix means descending. Defaults to -createdAt.
 * @pattern ^-?(createdAt|updatedAt|name|warrantyMonths)$
 */
sort?: string;
};
