/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Base quick reply representation (agent response templates, FR-008).
 */
export type ListQuickReplies200DataItem = {
  uuid: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  title: string;
  /**
     * Message body used as a reply template.
     * @minLength 1
     * @maxLength 4096
     */
  body: string;
  createdAt: string;
  updatedAt: string;
};
