/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListMessages200DataItem } from './listMessages200DataItem';
import type { ListMessages200Meta } from './listMessages200Meta';

/**
 * Envelope for the paginated message list.
 */
export type ListMessages200 = {
  data: ListMessages200DataItem[];
  meta: ListMessages200Meta;
};
