/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListCampaignsStatus } from './listCampaignsStatus';
import type { ListCampaignsType } from './listCampaignsType';

export type ListCampaignsParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exact match over the campaign status.
 */
status?: ListCampaignsStatus;
/**
 * Exact match over the campaign type.
 */
type?: ListCampaignsType;
/**
 * Case-insensitive partial match over the campaign name.
 */
search?: string;
/**
 * Field sorted by; "-" prefix means descending. Defaults to -createdAt.
 * @pattern ^-?(createdAt|updatedAt|name|status|type|startAt)$
 */
sort?: string;
};
