/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListCommercialCycles200DataItem } from './listCommercialCycles200DataItem';
import type { ListCommercialCycles200Meta } from './listCommercialCycles200Meta';

/**
 * Envelope for the paginated commercial cycle list.
 */
export type ListCommercialCycles200 = {
  data: ListCommercialCycles200DataItem[];
  meta: ListCommercialCycles200Meta;
};
