/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListCustomers200DataItem } from './listCustomers200DataItem';
import type { ListCustomers200Meta } from './listCustomers200Meta';

/**
 * Envelope for the paginated customer list.
 */
export type ListCustomers200 = {
  data: ListCustomers200DataItem[];
  meta: ListCustomers200Meta;
};
