/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListConversations200DataItem } from './listConversations200DataItem';
import type { ListConversations200Meta } from './listConversations200Meta';

/**
 * Envelope for the paginated conversation list.
 */
export type ListConversations200 = {
  data: ListConversations200DataItem[];
  meta: ListConversations200Meta;
};
