/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListImportJobs200DataItemErrorsSummary } from './listImportJobs200DataItemErrorsSummary';
import type { ListImportJobs200DataItemStatus } from './listImportJobs200DataItemStatus';
import type { ListImportJobs200DataItemType } from './listImportJobs200DataItemType';

/**
 * Import job. `filePath` and the full internal `errors` payload are never
 * exposed (NR-006, FR-024); only `errorsSummary` is returned.
 */
export type ListImportJobs200DataItem = {
  uuid: string;
  type: ListImportJobs200DataItemType;
  status: ListImportJobs200DataItemStatus;
  /** Original basename, sanitized (NR-006). */
  fileName: string;
  /** @minimum 0 */
  totalRecords: number;
  /** @minimum 0 */
  processedRecords: number;
  /** @minimum 0 */
  errorRecords: number;
  errorsSummary: ListImportJobs200DataItemErrorsSummary;
  /** @nullable */
  startedAt: string | null;
  /** @nullable */
  completedAt: string | null;
  createdAt: string;
  updatedAt: string;
};
