/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListFollowUpSequences200DataItem } from './listFollowUpSequences200DataItem';
import type { ListFollowUpSequences200Meta } from './listFollowUpSequences200Meta';

export type ListFollowUpSequences200 = {
  data: ListFollowUpSequences200DataItem[];
  /** Pagination metadata for collection responses. */
  meta: ListFollowUpSequences200Meta;
};
