/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListImportJobs200DataItem } from './listImportJobs200DataItem';
import type { ListImportJobs200Meta } from './listImportJobs200Meta';

/**
 * Envelope for the paginated import job list.
 */
export type ListImportJobs200 = {
  data: ListImportJobs200DataItem[];
  meta: ListImportJobs200Meta;
};
