/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { ListCampaigns200DataItem } from './listCampaigns200DataItem';
import type { ListCampaigns200Meta } from './listCampaigns200Meta';

/**
 * Envelope for the paginated campaign list.
 */
export type ListCampaigns200 = {
  data: ListCampaigns200DataItem[];
  meta: ListCampaigns200Meta;
};
