/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { Login200DataUserAccountType } from './login200DataUserAccountType';
import type { Login200DataUserRole } from './login200DataUserRole';
import type { Login200DataUserStatus } from './login200DataUserStatus';

/**
 * Identity v1 user profile and JWT context.
 */
export type Login200DataUser = {
  id: string;
  uuid: string;
  email: string;
  firstName: string;
  lastName: string;
  accountType: Login200DataUserAccountType;
  /** @nullable */
  organizationId: string | null;
  role: Login200DataUserRole;
  status: Login200DataUserStatus;
};
