/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

export type Login200DataUserRole = typeof Login200DataUserRole[keyof typeof Login200DataUserRole];


export const Login200DataUserRole = {
  PLATFORM_OWNER: 'PLATFORM_OWNER',
  ADMINISTRADOR: 'ADMINISTRADOR',
  GERENTE: 'GERENTE',
  OPERADOR: 'OPERADOR',
} as const;
