/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { Me200DataUserAccountType } from './me200DataUserAccountType';
import type { Me200DataUserRole } from './me200DataUserRole';
import type { Me200DataUserStatus } from './me200DataUserStatus';

/**
 * Identity v1 user profile and JWT context.
 */
export type Me200DataUser = {
  id: string;
  uuid: string;
  email: string;
  firstName: string;
  lastName: string;
  accountType: Me200DataUserAccountType;
  /** @nullable */
  organizationId: string | null;
  role: Me200DataUserRole;
  status: Me200DataUserStatus;
};
