/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { PreviewCampaignSegment200Data } from './previewCampaignSegment200Data';

/**
 * Dry-run segment resolution result. No automations are created and no PII is returned.
 */
export type PreviewCampaignSegment200 = {
  data: PreviewCampaignSegment200Data;
};
