/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Payload for an asesor reply to a conversation (HG-6).
 */
export type ReplyConversationBody = {
  /**
     * WhatsApp text body (PII — never logged).
     * @minLength 1
     * @maxLength 4096
     */
  content: string;
  /** Optional quick reply uuid used as the reply template (audit reference, FR-008). */
  quickReplyId?: string;
};
