/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { SendManualMessageBodyChannel } from './sendManualMessageBodyChannel';

/**
 * Payload for sending a manual WhatsApp message (WR-05, AS-004).
 */
export type SendManualMessageBody = {
  /** uuid of the recipient customer (must belong to the caller's organization). */
  customerId: string;
  /**
     * WhatsApp text body.
     * @minLength 1
     * @maxLength 4096
     */
  content: string;
  /** v1 only supports WHATSAPP_CLIENTS. */
  channel?: SendManualMessageBodyChannel;
};
