/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * v1 only supports WHATSAPP_CLIENTS.
 */
export type SendManualMessageBodyChannel = typeof SendManualMessageBodyChannel[keyof typeof SendManualMessageBodyChannel];


export const SendManualMessageBodyChannel = {
  WHATSAPP_CLIENTS: 'WHATSAPP_CLIENTS',
} as const;
