/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { SendManualMessage201Data } from './sendManualMessage201Data';

/**
 * Envelope for a single message resource.
 */
export type SendManualMessage201 = {
  /** Full message representation with customer context. */
  data: SendManualMessage201Data;
};
