/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { TransferConversation200DataAdvisor } from './transferConversation200DataAdvisor';

export type TransferConversation200Data = {
  uuid: string;
  /** @nullable */
  advisor: TransferConversation200DataAdvisor;
};
