/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { TransferConversation200Data } from './transferConversation200Data';

/**
 * Envelope for assign/transfer results (FR-004, HG-4).
 */
export type TransferConversation200 = {
  data: TransferConversation200Data;
};
