/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCustomerBodyStatus } from './updateCustomerBodyStatus';

/**
 * Request body to update a customer. codcli is immutable and rejected with 400 if present.
 */
export type UpdateCustomerBody = {
  /** Always rejected (400) — codcli is immutable. */
  codcli?: string;
  /** @maxLength 200 */
  name?: string;
  /** @maxLength 30 */
  phone?: string;
  email?: string;
  /** @maxLength 200 */
  address?: string;
  /** @maxLength 200 */
  city?: string;
  status?: UpdateCustomerBodyStatus;
};
