/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Full conversation tag representation (catalog detail).
 */
export type UpdateConversationTag200Data = ({
  uuid: string;
  /** @maxLength 50 */
  name: string;
  /**
     * Hex color, e.g. "#0EA5E9".
     * @nullable
     */
  color: string | null;
  /**
     * Number of active assignments (soft-deleted excluded).
     * @minimum 0
     */
  conversationCount: number;
  createdAt: string;
  updatedAt: string;
});
