/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { UpdatePurchase200Data } from './updatePurchase200Data';

/**
 * Envelope for a single purchase operation.
 */
export type UpdatePurchase200 = {
  /** Purchase entity as persisted (v1). */
  data: UpdatePurchase200Data;
};
