/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateConversationTag200Data } from './updateConversationTag200Data';

/**
 * Envelope for a single conversation tag resource.
 */
export type UpdateConversationTag200 = {
  /** Full conversation tag representation (catalog detail). */
  data: UpdateConversationTag200Data;
};
