/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProductBodyStatus } from './updateProductBodyStatus';

/**
 * Request body to update a product. code is immutable and rejected with 400.
 */
export type UpdateProductBody = {
  /**
     * Immutable after creation; attempts return 400 "code is immutable and cannot be updated".
     * @maxLength 50
     */
  code?: string;
  /** @maxLength 200 */
  name?: string;
  /**
     * Free-text category (no catalog in v1).
     * @maxLength 100
     */
  category?: string;
  /** No transitions workflow in v1. */
  status?: UpdateProductBodyStatus;
};
