/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCampaignBodySegmentCustomerStatus } from './updateCampaignBodySegmentCustomerStatus';
import type { UpdateCampaignBodySegmentWarrantyMonths } from './updateCampaignBodySegmentWarrantyMonths';

/**
 * Customer segment filter for campaign automations. All criteria combine with AND; at least one criterion is required when the segment is provided.
 */
export type UpdateCampaignBodySegment = {
  /**
     * Partial match, case-insensitive, over the customer city.
     * @maxLength 200
     */
  city?: string;
  /** uuid of the purchased product. */
  productId?: string;
  /**
     * Lower bound on purchaseDate. Date-only (`YYYY-MM-DD`) includes the
     * whole requested day.
     */
  purchaseFrom?: string;
  /**
     * Upper bound on purchaseDate. Date-only (`YYYY-MM-DD`) includes the
     * whole requested day.
     */
  purchaseTo?: string;
  customerStatus?: UpdateCampaignBodySegmentCustomerStatus;
  /**
     * Lower bound on the purchase warranty expiration date
     * (`warrantyExpiresAt`). Date-only (`YYYY-MM-DD`) includes the whole
     * requested day.
     */
  warrantyExpiresFrom?: string;
  /**
     * Upper bound on the purchase warranty expiration date
     * (`warrantyExpiresAt`). Date-only (`YYYY-MM-DD`) includes the whole
     * requested day.
     */
  warrantyExpiresTo?: string;
  /**
     * Warranty duration in months of the purchased product. Restricted to
     * the catalog values supported by Product/Purchase/FollowUpSequence.
     */
  warrantyMonths?: UpdateCampaignBodySegmentWarrantyMonths;
};
