/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateFollowUpSequenceBodyStagesItem } from './updateFollowUpSequenceBodyStagesItem';
import type { UpdateFollowUpSequenceBodyWarrantyMonths } from './updateFollowUpSequenceBodyWarrantyMonths';

/**
 * Payload to update a follow-up sequence. At least one field required.
 */
export type UpdateFollowUpSequenceBody = {
  /**
     * @minLength 1
     * @maxLength 120
     */
  name?: string;
  /** @maxLength 1000 */
  description?: string;
  /** Warranty duration in months. Cannot be changed if sequence is used by campaigns. */
  warrantyMonths?: UpdateFollowUpSequenceBodyWarrantyMonths;
  /**
     * Complete replacement of stages. Cannot be changed if sequence is used by campaigns.
     * Each stage must have unique offsetDays.
     * @minItems 1
     */
  stages?: UpdateFollowUpSequenceBodyStagesItem[];
};
