/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Temporal reference for offsetDays.
 * PURCHASE_DATE = offset measured from the purchase date;
 * WARRANTY_EXPIRY = offset measured from the warranty expiration date.
 * Defaults to WARRANTY_EXPIRY when omitted (preserves legacy behavior).
 */
export type UpdateFollowUpSequenceBodyStagesItemAnchor = typeof UpdateFollowUpSequenceBodyStagesItemAnchor[keyof typeof UpdateFollowUpSequenceBodyStagesItemAnchor];


export const UpdateFollowUpSequenceBodyStagesItemAnchor = {
  PURCHASE_DATE: 'PURCHASE_DATE',
  WARRANTY_EXPIRY: 'WARRANTY_EXPIRY',
} as const;
