/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCampaignBodySegment } from './updateCampaignBodySegment';
import type { UpdateCampaignBodyType } from './updateCampaignBodyType';

/**
 * Partial update of a campaign. Only allowed while the campaign is DRAFT;
 * at least one field must be provided. The segment, when present, must
 * include at least one criterion.
 */
export type UpdateCampaignBody = {
  /**
     * @minLength 1
     * @maxLength 120
     */
  name?: string;
  /** @maxLength 1000 */
  description?: string;
  type?: UpdateCampaignBodyType;
  /**
     * @minLength 1
     * @maxLength 4096
     */
  template?: string;
  /** Message for the +3 days stage. When defined, replaces `template` for that stage. */
  templateD3?: string;
  /** Message for the +6 months stage. When defined, replaces `template` for that stage. */
  templateD180?: string;
  /** Message for the +12 months stage. When defined, replaces `template` for that stage. */
  templateD365?: string;
  /** Customer segment filter for campaign automations. All criteria combine with AND; at least one criterion is required when the segment is provided. */
  segment?: UpdateCampaignBodySegment;
  startAt?: string;
};
