/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { UpdatePurchase200DataStatus } from './updatePurchase200DataStatus';

/**
 * Purchase entity as persisted (v1).
 */
export type UpdatePurchase200Data = {
  id: string;
  uuid: string;
  organizationId: string;
  /** Reference to the customer of the purchase (immutable). */
  customerId: string;
  /** Reference to the product of the purchase (immutable). */
  productId: string;
  /**
     * Immutable after creation. Part of the uniqueness tuple (CP-005).
     * @maxLength 50
     */
  invoiceNumber: string;
  purchaseDate: string;
  /** @minimum 1 */
  quantity: number;
  /**
     * Total purchase value in USD as a string, two decimal places max (HG-7).
     * @pattern ^\d{1,10}(\.\d{1,2})?$
     */
  value: string;
  /** Defaults to COMPLETED. Changed freely via PATCH in v1 (HG-7). */
  status: UpdatePurchase200DataStatus;
  /**
     * Effective warranty duration in months (product default or explicit override at creation); null when the product has no warranty.
     * @nullable
     */
  warrantyMonths?: number | null;
  /**
     * Warranty expiration computed as purchaseDate + warrantyMonths; null when the product has no warranty.
     * @nullable
     */
  warrantyExpiresAt?: string | null;
  createdAt: string;
  updatedAt: string;
  /**
     * Reserved and inert in v1 (HG-4); there is no DELETE endpoint.
     * @nullable
     */
  deletedAt?: string | null;
  /**
     * User id that created the record.
     * @nullable
     */
  createdBy?: string | null;
  /**
     * User id of the last update.
     * @nullable
     */
  updatedBy?: string | null;
};
