/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateQuickReply200Data } from './updateQuickReply200Data';

/**
 * Envelope for a single quick reply resource.
 */
export type UpdateQuickReply200 = {
  /** Full quick reply representation (catalog detail). */
  data: UpdateQuickReply200Data;
};
