/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */

/**
 * Changed freely without transitional rules (HG-7).
 */
export type UpdatePurchaseBodyStatus = typeof UpdatePurchaseBodyStatus[keyof typeof UpdatePurchaseBodyStatus];


export const UpdatePurchaseBodyStatus = {
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
} as const;
