/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Automatize It API
 * API oficial de Automatize It.
 *
 * Permite administrar clientes, compras, campañas,
 * automatizaciones, conversaciones y mensajería mediante
 * WhatsApp Cloud API.
 *
 * OpenAPI spec version: 1.0.0
 */
import type { UpdatePurchaseBodyStatus } from './updatePurchaseBodyStatus';

/**
 * Request body to update a purchase. invoiceNumber is immutable and rejected with 400 if present. customerId and productId are immutable and ignored by the whitelist.
 */
export type UpdatePurchaseBody = {
  /** Always rejected (400) — invoiceNumber is immutable. */
  invoiceNumber?: string;
  purchaseDate?: string;
  /**
     * Units of the purchase; capped at the Prisma Int maximum (int4).
     * @minimum 1
     * @maximum 2147483647
     */
  quantity?: number;
  /**
     * Total purchase value in USD as a string.
     * @pattern ^\d{1,10}(\.\d{1,2})?$
     */
  value?: string;
  /** Changed freely without transitional rules (HG-7). */
  status?: UpdatePurchaseBodyStatus;
};
